### PR TITLE
added Hash Table

### PR DESCRIPTION
**Pull request by ashokdey**
🌮 What's Inside?

Added the most extensively used Data Structure - **Hash Tables** (aka Hash Map)

API Details:
- set(key, value): to set the key-value pair
- get(key): to get the value(s) associated with the given key
- delete(key): remove the key and the associated values

**Note**: Passing the same key with different value, overrides the previous value

🏖

### CODE REVIEW

**Comment by TheSTL** [comment]
In `remove` method instead of creating whole new linked list, manipulating the existing one will be a better approach i think because old linked list will remain in memory. @ashokdey

**Comment by ashokdey** [comment]
> In `remove` method instead of creating whole new linked list, manipulating the existing one will be a better approach i think because old linked list will remain in memory. @ashokdey

@TheSTL raise a PR with this branch for the same

**Comment by ashokdey** [comment]
> In `remove` method instead of creating whole new linked list, manipulating the existing one will be a better approach i think because old linked list will remain in memory. @ashokdey

I've updated it but would like to see your approach as well 👍

**Comment by TheSTL** [comment]
@ashokdey  `get` function returns an array. I'm not able to understand why? It should return the `value`

**Comment by ashokdey** [comment]
> @ashokdey `get` function returns an array. I'm not able to understand why? It should return the `value`

Because I am not able to finalize either to override a value when the same key is used more than once. For example: 
```javascript
ht.set('hello', 'Hello Hash Table');
ht.set('hello', 'Hello World');
```

**Pull request merged**
