### PR TITLE
Add unit tests to Max Product of 3 numbers problem

### PR DESCRIPTION
**Pull request by LeoSL**
## 🐻 What's inside?

- Add unit tests to Max Product of 3 numbers problem
- Export function to be used by test file

### 🚨**Issue found**

Since the problem specifies the product of **exactly 3 numbers** I was about to write the following test...

```js
it("returns an error if there are less than 3 numbers", () => {
  expect(() => {
    maxProductof3Numbers([-10, -1]);
  }).toThrowError();
});
```

But this case is not covered by the implementation. Should I implement this test scenario?

### CODE REVIEW

**Comment by ashokdey** [comment]
Thanks for the PR @LeoSL, really good to see the edge case you pointed out. @TheSTL will carry on with this PR. 

All the best 👍

**Comment by TheSTL** [comment]
Thanks @LeoSL .
I implement this scenario in this Pr [#28 ](https://github.com/knaxus/problem-solving-javascript/pull/28).
Now you can implement test scenario where array length is less than 3.

**Comment by ashokdey** [comment]
> ## 🐻 What's inside?
> * Add unit tests to Max Product of 3 numbers problem
> * Export function to be used by test file
> 
> ### 🚨**Issue found**
> Since the problem specifies the product of **exactly 3 numbers** I was about to write the following test...
> 
> ```js
> it("returns an error if there are less than 3 numbers", () => {
>   expect(() => {
>     maxProductof3Numbers([-10, -1]);
>   }).toThrowError();
> });
> ```
> 
> But this case is not covered by the implementation. Should I implement this test scenario?

Hello @LeoSL, since @TheSTL has handled the edge case, you can move forward to implement the test case.

**Comment by LeoSL** [comment]
Hey @ashokdey @TheSTL , thank you for the quick response and action.

I went ahead and committed the test case on this PR. Let me know if there are other details to fix.

**Pull request merged**
