### PR TITLE
Fix Fibonacci problem for negative numbers

### LINKED ISSUE #42: Handling fibonacci for negative numbers and 0
Function **fibonacciTabular** is not handled if a negative number is provided. It returns undefined as output.

If 0 is given as index in **fibonacciTabular** it returns 0 instead of 1.

@ashokdey For the functions **fibonacci** and **fibonacciMemoized** if negative numbers are provided the output is coming as 1. Is it correct to handle in such a way that the output should be 1 or it should be handled that the output comes as 0?

### PR DESCRIPTION
**Pull request by SumeetHaryani**
Fix Fibonacci problem for negative numbers.
Fixes #42

### CODE REVIEW

**Comment by SumeetHaryani** [comment]
Fixes #58

**Comment by TheSTL** [comment]
Hey @SumeetHaryani .
Right now queue data is not implemented in right way.
I am opening a new issue for this. You can change `reverse-first-k-elements-of-queue` implementation after that.

**Comment by TheSTL** [comment]
@SumeetHaryani  
If it's okay can you remove `reverse-first-k-elements-of-queue` implementation from this PR.
And when this issue [#60 ](https://github.com/knaxus/problem-solving-javascript/issues/60) is fixed by @ashokdey you can create a new PR for your algo.

**Comment by SumeetHaryani** [comment]
@TheSTL , I have removed `reverse-first-k-elements-of-queue` implementation from this PR. 
Will add it once @ashokdey  fixes the #60

**Pull request merged**
