### PR TITLE
Fixes for bug #61

### PR DESCRIPTION
**Pull request by k88manish**
- Added test cases for error cases
- Handled invalid expression
- ESLint error fixes

### CODE REVIEW

**Comment by k88manish** [comment]
Hi @ashokdey, @TheSTL. I have made the fixes for #61. Please review it help me to merge it.

**Comment by TheSTL** [comment]
@k88manish We are not getting your commit properly . Please setup you git properly.
image

**Comment by TheSTL** [comment]
When stack is not empty or expression is not there is should throw an error instead of returning a string. You can check this problem to get idea and then write test case accordingly - [fibonacci](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_Classics_/fibonacci/index.js)

**Comment by k88manish** [comment]
Hi @TheSTL, Thanks for reviewing it. I have made the changes to replace string message with throw error. Can you please review it again?

**Comment by TheSTL** [comment]
@k88manis

> @k88manish We are not getting your commit properly . Please setup you git properly.
> image

Not getting your commit.
Please fix this

**Comment by manishkumar-xebia** [comment]
Hi @TheSTL,  I did check my git and it seems to be fine. Can you let me know what exactly is happening with that commit?  I was doing multiline comment that's why it is showing like that

**Comment by TheSTL** [comment]
@k88manish I think it will work [commits-are-not-getting-linked-with-github-account ](https://stackoverflow.com/questions/26004587/git-commits-are-not-getting-linked-with-my-github-account).
And please also check this issue for your other PRs

**Comment by k88manish** [comment]
closing this pull request because the Author information is not correct. Will open a new one

**Pull request closed without merging**
