### PR TITLE
Add unit tests for suffix tree

### LINKED ISSUE #87: Add Unit Test for - Suffix Tree
File location : [Suffix tree](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Trees/SuffixTree/index.js)
Hello folks, please go through the Contribution Guide here [https://github.com/knaxus/problem-solving-javascript#contribution-guide](https://github.com/knaxus/problem-solving-javascript#contribution-guide) before going forward with this issue. 

Thanks

### PR DESCRIPTION
**Pull request by faergeek**
Fixes #87

Not sure if these tests are enough. Can't think of something more. Can you take a look?

### CODE REVIEW

**Comment by TheSTL** [comment]
Hi @faergeek can you add few more cases ? Now test cases are weak.

**Comment by faergeek** [comment]
To be honest, I am not sure which test cases would not be weak. May be I just don't get it. Do you have some advice?

**Comment by TheSTL** [comment]
@faergeek For example take test cases where suffix tree made from a string should have height minimum 3 .
`mississippi`
image
OR

constructed suffix tree is like a linked list. `aaaaaaaaaaa`

These are the few cases i come with. @faergeek

**Comment by faergeek** [comment]
Thanks! I added these cases. BTW why is there separate method for constructing suffix tree? Why it isn't done in constructor?

**Comment by faergeek** [comment]
More than a month passed. Do I stiil need to fix something here?

**Comment by TheSTL** [comment]
Sorry ,I have been busy lately. 
PR is good to go :+1:

**Pull request merged**
