### PR TITLE
Armstrong Number solved

### LINKED ISSUE #113: Armstrong No.
I would gladly take up the task for adding Armstrong no.

### PR DESCRIPTION
**Pull request by Omkaragrawal**
Fixed #113 added armstrong number.

### CODE REVIEW

**Comment by Omkaragrawal** [comment]
hey, @TheSTL  can you help me with what is the failing check about?

**Comment by TheSTL** [comment]
By reading this post from [stack over flow](https://salesforce.stackexchange.com/questions/244794/how-do-i-increase-my-code-coverage-or-why-cant-i-cover-these-lines) I think coverage is decreased because some code lines are not covered in test cases. And we can get it by total test cases* code not covered in one test case.
Code not covered in single test case is because of `Control Structures`.
Example this code ` num = (!Number.isNaN(Number(num))) ? parseInt(Math.abs(Number(num)), 10).toString() : (() => { throw Error('error')`
@ashokdey @Omkaragrawal

**Comment by Omkaragrawal** [comment]
Hey,
@TheSTL  @ashokdey  so is it ok? If not what do I need to do for it, add a case that evaluates the error?

**Comment by TheSTL** [comment]
@Omkaragrawal I think Armstrong Number should not be tested for decimals. It should throw error for decimal number or any other input except Integer.
- Remove tests for decimals.
- Add test cases where it should except to throw error

**Comment by Omkaragrawal** [comment]
Hey, there are some minor changes in the test that's it, give me some time since I have my University exams till 28th.

**Comment by ashokdey** [comment]
Ok.

**Comment by Omkaragrawal** [comment]
Hey @ashokdey  I regret that I totally forgot about this. I will get to this soon and rewrite the tests.

**Pull request closed without merging**
