### PR TITLE
Created Ternary_serach.c using C

### PR DESCRIPTION
**Pull request by Avinash11a**
C program to illustrate iterative approach to ternary search

### CODE REVIEW

**Comment by ashokdey** [comment]
@Avinash11a, appreciate your efforts but cannot merge it here.

**Comment by Avinash11a** [comment]
Whats the problem, Can I open the PR again ?

**Comment by TheSTL** [comment]
This is a JavaScript repository @Avinash11a

**Comment by Avinash11a** [comment]
Can I again post in javascript?

**Comment by TheSTL** [comment]
PR for this issue is already merged.

**Comment by TheSTL** [comment]
You can work on other issues.

**Pull request closed without merging**
